DELIMITER //
CREATE TRIGGER DeletePost
AFTER DELETE
ON post FOR EACH ROW
BEGIN
IF (SELECT COUNT(*) FROM employee WHERE post=old.post)>0
THEN SIGNAL SQLSTATE  '45000'
	SET MESSAGE_TEXT = 'Can`t delete post';
END IF;
END //
DELIMITER ;

DROP  TRIGGER DeletePost;